name: Terraform provider cache example

on:
  workflow_dispatch:

jobs:
  main:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-
      - name: Init Terraform configuration
        run: |
          terraform init
  plan:
    name: plan
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - run: |
          terraform init
          terraform plan
    
